notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 15

linux: &linux
  os: linux
  dist: xenial
  language: python
  python: "3.7"
  services:
    - docker

osx: &osx
  os: osx
  sudo: false
  language: generic


jobs:
  fast_finish: true # don't wait for allow_failures to fail, gives faster response
  allow_failures:
    - os: osx
  include:
  - stage: "Building & Testing"
    <<: *linux
    env: COMPILER="clang" COMPILER_VERSION="5.0" BUILD_TYPE="Release" TARGET="compile" NIGHTLY="true"
  - <<: *linux
    env: COMPILER="gcc" COMPILER_VERSION="7" BUILD_TYPE="Release" TARGET="compile" NIGHTLY="true"
  - stage: "Docs"
    os: linux
    sudo: false
    dist: trusty
    addons:
      apt:
        packages:
          - doxygen
    env: DOCKER="NODOCKER" TARGET="apidoc"
  - stage: "Create GitHub Tag"
    os: linux
    sudo: false
    dist: trusty
    env: DOCKER="NODOCKER" TARGET="new_version_tagger"
    branches:
      only:
        - master

before_install:
  # Get our CI Docker image
  - if [ -z "${DOCKER}" ]; then
        docker_version=$(echo ${COMPILER_VERSION} | sed -e 's/\.//g');
        DOCKER="conanio/"${COMPILER}${docker_version};
        echo ${DOCKER};
    fi;
    if ! [[ "${DOCKER}" == 'NODOCKER' ]]; then
        sudo docker pull ${DOCKER} ;
    fi

script:
  - set -e;
  - if [ "${GLOBAL_NIGHTLY}" == "false" ]; then
      NIGHTLY="false";
    fi
  - if [ "${GLOBAL_NIGHTLY}" == "conanforcerebuild" ]; then
      TARGET="conanforcerebuild";
    fi
  - if [[ "${TRAVIS_REPO_SLUG}" == "inexorgame/inexor-core" ]]; then
      if [[ ! "${TRAVIS_PULL_REQUEST}" == false ]]; then
        echo >&2 -e "Skipping build, because this is a pull " \
          "request with a branch in the main repo.\n"         \
          "This means, there should already be a CI job for " \
          "this branch. No need to do things twice.";
        exit 0;
      fi;
    fi;
    if ! [[ "${DOCKER}" == "NODOCKER" ]]; then
      sudo docker run -v $(pwd)':'/inexor --net=host -it ${DOCKER} /inexor/tool/travis.sh ${TARGET} ${COMPILER} ${COMPILER_VERSION} ${BUILD_TYPE} ${NIGHTLY} ${CONAN_USER} ${CONAN_PASSWORD};
    fi;
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      bash tool/travis_macos.sh;
    fi;
  - if [ "${TARGET}" == "new_version_tagger" ]; then
      if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
        bash ./tool/travis.sh ${TARGET} ${COMPILER} ${COMPILER_VERSION} ${BUILD_TYPE} ${NIGHTLY} ${CONAN_USER} ${CONAN_PASSWORD};
      else
        echo >&2 -e "\n===============\n" \
        "Skipping tag creation, because this is \n" \
        "not a direct commit to master.\n" \
        "===============\n";
        exit 0;
      fi
    fi
  - if [ "${TARGET}" == "apidoc" ]; then
      chmod +x ./tool/documentation_create.sh && chmod +x ./tool/documentation_deploy.sh && source ./tool/documentation_deploy.sh;
    fi

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    - secure: DgFzibKfjjD4v6zP51sjyP+chyBNKA6D3LHz4+pKN2mSBLSFeqK29z+38TlIOJHSpq6pWdvxqHjn+vQuYV1v/oqri0AVpo0kxFojtNaIFo1Dc/Sfv76V7X6p9+JaSRtKtqCjOV7QP9fftyUgSu1Bq67fwuv6QvDgOzdQIcV87bA=
  file_glob: true
  file: build/cpack/inexor-core-*.zip
  overwrite: true
  on:
    # Deploy only if build was caused by a tag push.
    tags: true
    condition: "$COMPILER = clang"
    repo: inexorgame/inexor-core
